# Generated by Django 6.0.3 on 2026-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills e.g. Plumbing, Welding', max_length=300)),
                ('hourly_wage', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in KES', max_digits=8, null=True)),
                ('hours_per_day', models.PositiveIntegerField(blank=True, help_text='Comfortable working hours per day', null=True)),
                ('working_days', models.CharField(blank=True, help_text='Comma-separated days e.g. Mon,Tue,Wed', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='skillsync_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='skillsync_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
